dist:                       xenial

language:                   python

python:                     3.7

cache:                      pip

jobs:
  include:
    - stage:                Testing

      install:
          - pip install -r requirements.txt
          - pip install codecov

      script:
          - coverage run echo.py -v

      after_success:
          - codecov
